
package com.example;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CcApi", targetNamespace = "http://impl.bulkSms.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CcApi {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIp", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.GetIp")
    @ResponseWrapper(localName = "getIpResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.GetIpResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/getIpRequest", output = "http://impl.bulkSms.ws/CcApi/getIpResponse")
    public String getIp();

    /**
     * 
     * @param cpCode
     * @param password
     * @param taxCode
     * @param user
     * @return
     *     returns com.example.ResultCp
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsGetCpCode", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsGetCpCode")
    @ResponseWrapper(localName = "wsGetCpCodeResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsGetCpCodeResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsGetCpCodeRequest", output = "http://impl.bulkSms.ws/CcApi/wsGetCpCodeResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://impl.bulkSms.ws/CcApi/wsGetCpCode/Fault/Exception")
    })
    public ResultCp wsGetCpCode(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "TaxCode", targetNamespace = "")
        String taxCode)
        throws Exception_Exception
    ;

    /**
     * 
     * @param cpCode
     * @param password
     * @param user
     * @return
     *     returns com.example.CpBalance
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkBalance", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.CheckBalance")
    @ResponseWrapper(localName = "checkBalanceResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.CheckBalanceResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/checkBalanceRequest", output = "http://impl.bulkSms.ws/CcApi/checkBalanceResponse")
    public CpBalance checkBalance(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode);

    /**
     * 
     * @param cpCode
     * @param password
     * @param receiverID
     * @param requestID
     * @param commandCode
     * @param serviceID
     * @param user
     * @param userID
     * @param contentType
     * @param content
     * @return
     *     returns com.example.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsCpMt", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMt")
    @ResponseWrapper(localName = "wsCpMtResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMtResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsCpMtRequest", output = "http://impl.bulkSms.ws/CcApi/wsCpMtResponse")
    public Result wsCpMt(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "RequestID", targetNamespace = "")
        String requestID,
        @WebParam(name = "UserID", targetNamespace = "")
        String userID,
        @WebParam(name = "ReceiverID", targetNamespace = "")
        String receiverID,
        @WebParam(name = "ServiceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "CommandCode", targetNamespace = "")
        String commandCode,
        @WebParam(name = "Content", targetNamespace = "")
        String content,
        @WebParam(name = "ContentType", targetNamespace = "")
        String contentType);

    /**
     * 
     * @param cpCode
     * @param password
     * @param receiverID
     * @param requestID
     * @param commandCode
     * @param serviceID
     * @param user
     * @param userID
     * @param contentType
     * @param content
     * @return
     *     returns com.example.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsCpMtRegDlr", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMtRegDlr")
    @ResponseWrapper(localName = "wsCpMtRegDlrResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMtRegDlrResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsCpMtRegDlrRequest", output = "http://impl.bulkSms.ws/CcApi/wsCpMtRegDlrResponse")
    public Result wsCpMtRegDlr(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "RequestID", targetNamespace = "")
        String requestID,
        @WebParam(name = "UserID", targetNamespace = "")
        String userID,
        @WebParam(name = "ReceiverID", targetNamespace = "")
        String receiverID,
        @WebParam(name = "ServiceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "CommandCode", targetNamespace = "")
        String commandCode,
        @WebParam(name = "Content", targetNamespace = "")
        String content,
        @WebParam(name = "ContentType", targetNamespace = "")
        String contentType);

    /**
     * 
     * @param cpCode
     * @param password
     * @param messageIds
     * @param user
     * @return
     *     returns com.example.ResultDlr
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDlrStatus", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.GetDlrStatus")
    @ResponseWrapper(localName = "getDlrStatusResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.GetDlrStatusResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/getDlrStatusRequest", output = "http://impl.bulkSms.ws/CcApi/getDlrStatusResponse")
    public ResultDlr getDlrStatus(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "MessageIds", targetNamespace = "")
        String messageIds);

    /**
     * 
     * @param cpCode
     * @param password
     * @param senderCpCode
     * @param receiverID
     * @param requestID
     * @param commandCode
     * @param serviceID
     * @param user
     * @param userID
     * @param contentType
     * @param content
     * @return
     *     returns com.example.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsCpMt2", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMt2")
    @ResponseWrapper(localName = "wsCpMt2Response", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMt2Response")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsCpMt2Request", output = "http://impl.bulkSms.ws/CcApi/wsCpMt2Response")
    public Result wsCpMt2(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "RequestID", targetNamespace = "")
        String requestID,
        @WebParam(name = "UserID", targetNamespace = "")
        String userID,
        @WebParam(name = "ReceiverID", targetNamespace = "")
        String receiverID,
        @WebParam(name = "ServiceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "CommandCode", targetNamespace = "")
        String commandCode,
        @WebParam(name = "Content", targetNamespace = "")
        String content,
        @WebParam(name = "ContentType", targetNamespace = "")
        String contentType,
        @WebParam(name = "senderCpCode", targetNamespace = "")
        String senderCpCode);

    /**
     * 
     * @param cpCode
     * @param msg
     * @param password
     * @param requestID
     * @param commandCode
     * @param serviceID
     * @param user
     * @param contentType
     * @return
     *     returns com.example.ResultMultiReceiver
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsCpMt4", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMt4")
    @ResponseWrapper(localName = "wsCpMt4Response", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpMt4Response")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsCpMt4Request", output = "http://impl.bulkSms.ws/CcApi/wsCpMt4Response")
    public ResultMultiReceiver wsCpMt4(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "RequestID", targetNamespace = "")
        String requestID,
        @WebParam(name = "ServiceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "CommandCode", targetNamespace = "")
        String commandCode,
        @WebParam(name = "ContentType", targetNamespace = "")
        String contentType,
        @WebParam(name = "Msg", targetNamespace = "")
        List<MsgRequest> msg);

    /**
     * 
     * @param cpCode
     * @param password
     * @param user
     * @param timeReport
     * @return
     *     returns java.util.List<com.example.ReportHourBO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsReportHour", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsReportHour")
    @ResponseWrapper(localName = "wsReportHourResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsReportHourResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsReportHourRequest", output = "http://impl.bulkSms.ws/CcApi/wsReportHourResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://impl.bulkSms.ws/CcApi/wsReportHour/Fault/Exception")
    })
    public List<ReportHourBO> wsReportHour(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "timeReport", targetNamespace = "")
        String timeReport)
        throws Exception_Exception
    ;

    /**
     * 
     * @param cpCode
     * @param password
     * @param endDate
     * @param user
     * @param startDate
     * @return
     *     returns java.util.List<com.example.ReportDailyBO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsReportDaily", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsReportDaily")
    @ResponseWrapper(localName = "wsReportDailyResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsReportDailyResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsReportDailyRequest", output = "http://impl.bulkSms.ws/CcApi/wsReportDailyResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://impl.bulkSms.ws/CcApi/wsReportDaily/Fault/Exception")
    })
    public List<ReportDailyBO> wsReportDaily(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate)
        throws Exception_Exception
    ;

    /**
     * 
     * @param cpCode
     * @param password
     * @param startMonth
     * @param endMonth
     * @param user
     * @return
     *     returns java.util.List<com.example.ReportMonthBO>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsReportMonth", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsReportMonth")
    @ResponseWrapper(localName = "wsReportMonthResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsReportMonthResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsReportMonthRequest", output = "http://impl.bulkSms.ws/CcApi/wsReportMonthResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://impl.bulkSms.ws/CcApi/wsReportMonth/Fault/Exception")
    })
    public List<ReportMonthBO> wsReportMonth(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "startMonth", targetNamespace = "")
        String startMonth,
        @WebParam(name = "endMonth", targetNamespace = "")
        String endMonth)
        throws Exception_Exception
    ;

    /**
     * 
     * @param cpCode
     * @param date
     * @param password
     * @param pageNumber
     * @param alias
     * @param pageSize
     * @param username
     * @return
     *     returns com.example.FailSubReponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFailSub", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.GetFailSub")
    @ResponseWrapper(localName = "getFailSubResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.GetFailSubResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/getFailSubRequest", output = "http://impl.bulkSms.ws/CcApi/getFailSubResponse")
    public FailSubReponse getFailSub(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "cpCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "alias", targetNamespace = "")
        String alias,
        @WebParam(name = "date", targetNamespace = "")
        String date,
        @WebParam(name = "pageNumber", targetNamespace = "")
        String pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "")
        String pageSize);

    /**
     * 
     * @param cpCode
     * @param password
     * @param commandCode
     * @param requestMt
     * @param user
     * @return
     *     returns com.example.CreateMtResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsCpBatchMt", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpBatchMt")
    @ResponseWrapper(localName = "wsCpBatchMtResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsCpBatchMtResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsCpBatchMtRequest", output = "http://impl.bulkSms.ws/CcApi/wsCpBatchMtResponse")
    public CreateMtResult wsCpBatchMt(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "CommandCode", targetNamespace = "")
        String commandCode,
        @WebParam(name = "requestMt", targetNamespace = "")
        List<RequestMt> requestMt);

    /**
     * 
     * @param cpCode
     * @param commandCode
     * @param packageId
     * @param saleOrderId
     * @param orderNum
     * @param userID
     * @param content
     * @param password
     * @param receiverID
     * @param requestID
     * @param serviceID
     * @param user
     * @param contentType
     * @return
     *     returns com.example.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wsEcomCpMt", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsEcomCpMt")
    @ResponseWrapper(localName = "wsEcomCpMtResponse", targetNamespace = "http://impl.bulkSms.ws/", className = "com.example.WsEcomCpMtResponse")
    @Action(input = "http://impl.bulkSms.ws/CcApi/wsEcomCpMtRequest", output = "http://impl.bulkSms.ws/CcApi/wsEcomCpMtResponse")
    public Result wsEcomCpMt(
        @WebParam(name = "User", targetNamespace = "")
        String user,
        @WebParam(name = "Password", targetNamespace = "")
        String password,
        @WebParam(name = "CPCode", targetNamespace = "")
        String cpCode,
        @WebParam(name = "RequestID", targetNamespace = "")
        String requestID,
        @WebParam(name = "UserID", targetNamespace = "")
        String userID,
        @WebParam(name = "ReceiverID", targetNamespace = "")
        String receiverID,
        @WebParam(name = "ServiceID", targetNamespace = "")
        String serviceID,
        @WebParam(name = "CommandCode", targetNamespace = "")
        String commandCode,
        @WebParam(name = "Content", targetNamespace = "")
        String content,
        @WebParam(name = "ContentType", targetNamespace = "")
        String contentType,
        @WebParam(name = "SaleOrderId", targetNamespace = "")
        String saleOrderId,
        @WebParam(name = "PackageId", targetNamespace = "")
        String packageId,
        @WebParam(name = "OrderNum", targetNamespace = "")
        String orderNum);

}
